# Change these first
owner: articuana # Your GitHub organization or username, where this repository lives
repo: taller_uptime2 # The name of this repository

sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: YouTube
    url: https://www.youtube.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  baseUrl: /taller_uptime2
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime Status
  introTitle: "**Upptime** - Estado de los Servicios"
  introMessage: Página de estado en tiempo real impulsada por GitHub Actions.
  navbar:
    - title: Estado
      href: /
    - title: GitHub
      href: https://github.com/articuana/taller_uptime2
